apiVersion: batch/v1
kind: Job
metadata:
  name: download-source12
spec:
  template:
    spec:
      containers:
      - name: gsutil
        image: gcr.io/cloud-builders/gsutil
        args: ['cp', 'gs://aprindle-stuff/tensor.tar.gz',
        '/mnt']
        volumeMounts:
        - mountPath: /mnt
          name: pd
      volumes:
      - name: pd
        gcePersistentDisk:
          pdName: my-disk-4
      restartPolicy: Never
  backoffLimit: 4
